language: java
matrix:
  include:
  - jdk: oraclejdk7
    os: linux
  - os: osx
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- mvn test && mvn clean verify
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
